# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts "Seeding..."

diver1 = Diver.create(name: "Charlie Brown", country_from: "USA", diver_cert_level: "Open Water", age: 29, disclaimer: true, email: "i<3diving@gmail.com", password_digest: "1234567", avatar: Faker::Avatar.image(size: "50x50", format: 'png'))
diver2 = Diver.create(name: "Jon Snow", country_from: "Israel", diver_cert_level: "Dive Master", age: 31, disclaimer: true, email: "diving4life@gmail.com", password_digest: "1234567", avatar: Faker::Avatar.image(size: "50x50", format: 'png'))
diver3 = Diver.create(name: "Captain Kirk", country_from: "USA", diver_cert_level: "Advanced Open Water", age: 44, disclaimer: true, email: "boldlygo@gmail.com", password_digest: "1234567", avatar: Faker::Avatar.image(size: "50x50", format: 'png'))
diver4 = Diver.create(name: "Khan!!", country_from: "Australia", diver_cert_level: "Open Water", age: 92, disclaimer: true, email: "revengetokirk@gmail.com", password_digest: "1234567", avatar: Faker::Avatar.image(size: "50x50", format: 'png'))
diver5 = Diver.create(name: "Gorn", country_from: "China", diver_cert_level: "Rescue Diver", age: 57, disclaimer: true, email: "eat@gmail.com", password_digest: "1234567", avatar: Faker::Avatar.image(size: "50x50", format: 'png'))
diver6 = Diver.create(name: "Horse", country_from: "Tanzania", diver_cert_level: "Open Water", age: 22, disclaimer: true, email: "hello@gmail.com", password_digest: "1234567", avatar: Faker::Avatar.image(size: "50x50", format: 'png'))

a1 = Animal.create(name: "Trigger Fish", species_name: , size: 75, image_url: , dangerous: true, description: "A tropical fish that comes in a variety of colors. Commonly found with large, venemous barb.")
a2 = Animal.create(name: "French Angelfish", species_name: "Pomacanthus paru", size: 25, image_url: , dangerous: false, description: "A tropical fish with black and yellow stripes.")
a3 = Animal.create(name: "Grey Angelfish", species_name: "Pomacanthus arcuatus", size: 25, image_url: , dangerous: false, description: "Juviniles look similar to the French Angelfish but become grey with age.")
a4 = Animal.create(name: "Queen Angelfish", species_name: "Holacanthus ciliaris", size: 35, image_url: , dangerous: false, description: "A tropical fish with a dark blue spot on its forehead. ")
a5 = Animal.create(name: "Rock Beauty Angelfish", species_name: "Holacanthus tricolor", size: 25, image_url: , dangerous: false, description: "A tropical fish with yellow ouline and black center.")
a6 = Animal.create(name: "Great Barracuda", species_name: "Sphyraena barracuda", size: 80, image_url: , dangerous: true, description: "A long, thin fish with large teeth. Very aggressive and can have a nasty bite.")
a7 = Animal.create(name: "Fairy Basslet", species_name: "Gramma loreto", size: 7, image_url: , dangerous: false, description: "A tropical fish with a purple front and yellow tale")
a8 = Animal.create(name: "Shortnose Batfish", species_name: "Ogcocephalus nasutus", size: 35, image_url: , dangerous: false, description: "A tropical fish that has a long pointed nose. It is shaped like a spade in a card deck.")
a9 = Animal.create(name: "Barfin Blenny", species_name: "Malacoctenus versicolor", size: 7, image_url: , dangerous: false, description: "A small, well camoflauged fish")
a10 = Animal.create(name: "Dusky Blenny", species_name: "Malacoctenus gilli", size: 7, image_url: , dangerous: false, description: "A small, well camoflauged fish")
a11 = Animal.create(name: "Goldline Blenny", species_name: "Malacoctenus aurolineatus", size: 7, image_url: , dangerous: false, description: "A small, well camoflauged fish")
a12 = Animal.create(name: "Hairy Blenny", species_name: "Labrisomus nuchipinnis", size: 7, image_url: , dangerous: false, description: "A small, well camoflauged fish. They are the largest blenny in the Caribbean region.")
a13 = Animal.create(name: "Mimic Blenny", species_name: "Labrisomus guppyi", size: 5, image_url: , dangerous: false, description: "This blenny is most often mis-identified as a Hairy Blenny. The mimic is smaller in size however.")
a14 = Animal.create(name: "Orangespotted Blenny", species_name: "Hypleurochilus springeri", size: 5, image_url: , dangerous: false, description: "A small, well camoflauged fish")
a15 = Animal.create(name: "Puffcheek Blenny", species_name: "Labrisomus bucciferus", size: 5, image_url: , dangerous: false, description: "Seldom seen because they hide under rock/coral rubble in shallow areas and small patch reef and rely on their perfect camouflage to avoid being seen.")
a16 = Animal.create(name: "Peal Blenny", species_name: "Entomacrodus nigricans", size: 5, image_url: , dangerous: false, description: "A small, well camoflauged fish")
a17 = Animal.create(name: "Redlip Blenny", species_name: "Ophioblennius macclurei", size: 5, image_url: , dangerous: false, description: "A small fish with a red head and red mouth.")
a18 = Animal.create(name: "Rosy Blenny", species_name: "Malacoctenus macropus", size: 5, image_url: , dangerous: false, description: "The male Rosy Blenny is distinguished from the female by the red spotted pattern on his lower cheeks and jaw.")
a19 = Animal.create(name: "Saddled Blenny", species_name: "Malacoctenus triangulatus", size: 5, image_url: , dangerous: false, description: "The Saddled Blenny has four saddles (with stirrups that cross below the mid-line on their sides). ")
a20 = Animal.create(name: "Honeycomb Cowfish", species_name: "Acanthostracion polygonia", size: 25, image_url: , dangerous: false, description: "A fish with various distinct polygon shaped markings on their body. They have a general box shape and two horns as well.")
a21 = Animal.create(name: "Scrawled Cowfish", species_name: "Acanthostracion quadricornis", size: 25, image_url: , dangerous: false, description: "A fish with various blue and yello splotches. Has two small horns.")
a22 = Animal.create(name: "Banded Butterflyfish", species_name: "Chaetodon striatus", size: 16, image_url: , dangerous: false, description: "A fish with black and white bands that run up and down its body.")
a23 = Animal.create(name: "Foureye Butterflyfish", species_name: "Chaetodon capistratus", size: 17, image_url: , dangerous: false, description: "A fish with two black spots on the back of its tail.")
a24 = Animal.create(name: "Spotfin Butterflyfish", species_name: "Chaetodon ocellatus", size: 17, image_url: , dangerous: false, description: "A fish with a black stripe on its head and yellow all around it's body.")
a25 = Animal.create(name: "Belted Cardinalfish", species_name: "Apogon townsendi", size: 7, image_url: , dangerous: false, description: "Small red fish with a black dot and a black stripe.")
a26 = Animal.create(name: "Blackfin Cardinalfish", species_name: "Astrapogon puncticulatus", size: 6, image_url: , dangerous: false, description: "A fish with a black all over its body.")
a27 = Animal.create(name: "Flamefish", species_name: "Apogon maculatus", size: 7, image_url: , dangerous: false, description: "A fish with red and black spots.")
a28 = Animal.create(name: "Bermuda Chub", species_name: "Kyphosus sectatrix", size: 40, image_url: , dangerous: false, description: "A fish with a small beak mouth and yellow stripes running along its body.")
a28 = Animal.create(name: "Beaugregory Damselfish", species_name: "Stegastes leucostictus", size: 7, image_url: , dangerous: false, description: "A small fish with blue-purple on the top of its body and yellow on its belly.")
a29 = Animal.create(name: "Bi-colored Damselfish", species_name: "Stegastes partitus", size: 7, image_url: , dangerous: false, description: "A small fish with blue-purple on the top of its body and yellow on its belly.")
a30 = Animal.create(name: "Cocoa Damselfish", species_name: "Stegastes veriabilis", size: 7, image_url: , dangerous: false, description: "A fish with a dark green/grey body.")
a31 = Animal.create(name: "Dusky Damselfish", species_name: "Stegastes adustus", size: 7, image_url: , dangerous: false, description: "A small fish with an orange top and black spot.")
a32 = Animal.create(name: "Longfin Damselfish", species_name: "Stegastes diencaeus", size: 7, image_url: , dangerous: false, description: "A small fish with blue spots and a yellow body.")
a33 = Animal.create(name: "Night Sergeant", species_name: "Abudefduf taurus", size: 20, image_url: , dangerous: false, description: "A fish with black and white stripes.")
a34 = Animal.create(name: "Sergeant Major", species_name: "Abudefduf saxatilis", size: 23, image_url: , dangerous: false, description: "A fish with black and white stripes.")
a35 = Animal.create(name: "Yellowtail Damselfish", species_name: "Microspathodon chrysurus", size: 20, image_url: , dangerous: false, description: "A fish with black body and bright blue dots.")
a36 = Animal.create(name: "Blue Chromis", species_name: "Azurina cyanea", size: 8, image_url: , dangerous: false, description: "A fish with black body and bright blue dots.")
a37 = Animal.create(name: "Chain Moray Eel", species_name: "Echidna catenata", size: 37, image_url: , dangerous: true, description: "An eel with yellow and black dots. Note: eels can have a nasty bite if provoked.")
a38 = Animal.create(name: "Chestnut Moray Eel", species_name: "Enchelycore carychroa", size: 30, image_url: , dangerous: true, description: "An eel with redish-brown color and white dots on its face. Note: eels can have a nasty bite if provoked.")
a39 = Animal.create(name: "Green Moray Eel", species_name: "Gymnothorax funebris", size: 150, image_url: , dangerous: true, description: "An eel with green all over its body. The largest of the Moray eels. Note: eels can have a nasty bite if provoked.")
a40 = Animal.create(name: "Peacock Flounder", species_name: "Bothus lunatus", size: 45, image_url: , dangerous: false, description: "An flat fish with two eyes on one side of its body. Generally lies on the ocean floor concealed in sand.")
a41 = Animal.create(name: "Graysby Grouper", species_name: "Cephalopholis cruentatus", size: 20, image_url: , dangerous: false, description: "Part of the seabass family, they are quite shy and will hide if they see your presence.")
a42 = Animal.create(name: "Nassau Grouper", species_name: "Epinephelus striatus", size: 100, image_url: , dangerous: false, description: "Part of the seabass family, they are a predatory fish with distinct yellow and black splotches")
a43 = Animal.create(name: "Indo-Pacific Lionfish", species_name: "Pterois volitans", size: 30, image_url: , dangerous: true, description: "An invasive, predatory species. Defined by their orange and white stripes with long, feathery fins that are venemous barbs. Use caution around them.")
a44 = Animal.create(name: "Princess Parrotfish", species_name: "Scarus taeniopterus", size: 23, image_url: , dangerous: false, description: "A fish with a small beak and multicolors of blue, purple, pink, and yellow.")
a45 = Animal.create(name: "Rainbow Parrotfish", species_name: "Scarus guacamaia", size: 25, image_url: , dangerous: false, description: "Similar to the Princess Rainbowfish, it has multiple colors on its body.")
a46 = Animal.create(name: "Balloonfish", species_name: "Diodon holocanthus", size: 40, image_url: , dangerous: false, description: "Also known as a Pufferfish, this fish can exapand its size and barbs along its body.")
a47 = Animal.create(name: "Lemon Shark", species_name: "Negaprion brevirostris", size: 250, image_url: , dangerous: true, description: "Even though an attack is extremely unlikely, shark attacks can happen if a shark is provoked or in the middle of a feeding frenzy. Be sure to have lots of space between you and the shark")
a48 = Animal.create(name: "Nurse Shark", species_name: "Ginglymostoma cirratum", size: 220, image_url: , dangerous: true, description: "Even though an attack is extremely unlikely, shark attacks can happen if a shark is provoked or in the middle of a feeding frenzy. Be sure to have lots of space between you and the shark")
a49 = Animal.create(name: "Blacktip Reef Shark", species_name: "Carcharhinus limbatus", size: 150, image_url: , dangerous: true, description: "Even though an attack is extremely unlikely, shark attacks can happen if a shark is provoked or in the middle of a feeding frenzy. Be sure to have lots of space between you and the shark")
a50 = Animal.create(name: "Bull Shark", species_name: "Carcharhinus leucas", size: 240, image_url: , dangerous: true, description: "Even though an attack is extremely unlikely, shark attacks can happen if a shark is provoked or in the middle of a feeding frenzy. Be sure to have lots of space between you and the shark")
a51 = Animal.create(name: "Spotted Eagle Ray", species_name: "Aetobatus narinari", size: 425, image_url: , dangerous: true, description: "Stingrays are a beautiful animal but the stinger can cause serious injury. Be sure to give the animal plenty of space.")
a52 = Animal.create(name: "Southern Stingray", species_name: "Aetobatus narinari", size: 67, image_url: , dangerous: true, description: "Stingrays are a beautiful animal but the stinger can cause serious injury. Be sure to give the animal plenty of space.")
a53 = Animal.create(name: "Spotted Caribbean Stingray", species_name: "Unknown", size: 60, image_url: , dangerous: true, description: "Stingrays are a beautiful animal but the stinger can cause serious injury and is venemous. Be sure to give the animal plenty of space.")
a54 = Animal.create(name: "Blue Tang", species_name: "Acanthurus coeruleus", size: 24, image_url: , dangerous: true, description: "Blue Tangs are a member of the Surgeonfish family which have venemous barbs on both sides of their body. Do not touch them.")
a55 = Animal.create(name: "Ocean Surgeonfish", species_name: "Acanthurus tractus", size: 27, image_url: , dangerous: true, description: "This fish member of the Surgeonfish family which have venemous barbs on both sides of their body. Do not touch them.")
a56 = Animal.create(name: "Doctorfish", species_name: "Acanthurus chirurgus", size: 26, image_url: , dangerous: true, description: "This fish is a member of the surgeonfish family which have venemous barbs on both sides of their body. Do not touch them.")



